### ISSUE TITLE
hardcoded instance names?

### ISSUE THREAD

**Issue by tbuser** [makerbot/conveyor#3]
Given this manifest:

{"namespace":"http:\/\/spec.makerbot.com\/ns\/thing.0.1.1.1","objects":{"20mmbox.stl":{}},"constructions":{"Extruder 1":{}},"instances":{"Instance 1":{"object":"20mmbox.stl","scale":"mm","construction":"Extruder 1"}},"attribution":{"author":"Spacexula","license":"Attribution - Share Alike - Creative Commons"}}

I get this error:

Traceback (most recent call last):
  File "/home/thingiv3rse/conveyor/src/main/python/conveyor/jsonrpc.py", line 392, in _invokemethod
    result = func(_args, *_kwargs)
  File "/home/thingiv3rse/conveyor/src/main/python/conveyor/server/__init__.py", line 101, in _slice
    task = recipe.slice(gcode)
  File "/home/thingiv3rse/conveyor/src/main/python/conveyor/recipe.py", line 221, in slice
    instance = self._getinstance_a()
  File "/home/thingiv3rse/conveyor/src/main/python/conveyor/recipe.py", line 162, in _getinstance_a
    instance = self._getinstance('plastic A')
  File "/home/thingiv3rse/conveyor/src/main/python/conveyor/recipe.py", line 159, in _getinstance
    raise Exception
Exception
conveyor: ERROR: task failed: {u'message': u'uncaught exception', u'code': -32000, u'data': {u'message': u'', u'args': [], u'name': u'Exception'}}
conveyor: ERROR: conveyor terminating with status code 1

It looks like the instance names are hard coded?

**Comment by tbuser** [comment]
Note: I got past this error by removing the construction lines from the manifest.

**Comment by msamsonoff** [comment]
Right now we only support two construction names: Plastic A and Plastic B. This will be fixed when we add materials to the s3g driver.
