### ISSUE TITLE
Conveyor service cant' start after reboot (conveyor (3.8.0-15.04)) on linux

### ISSUE THREAD

**Issue by jidar** [makerbot/conveyor#33]
Initial install of makerware works, after rebooting service won't start.

**Comment by sircambridge** [comment]
yup same here - get this

`Traceback (most recent call last):
  File "/usr/share/makerbot/python/conveyor-3.8.4-py2.7.egg/conveyor/error.py", line 444, in guard
    code = func()
  File "/usr/share/makerbot/python/conveyor-3.8.4-py2.7.egg/conveyor/main.py", line 72, in func
    code = self._run()
  File "/usr/share/makerbot/python/conveyor-3.8.4-py2.7.egg/conveyor/server/__main__.py", line 54, in _run
    listener = address.listen()
  File "/usr/share/makerbot/python/conveyor-3.8.4-py2.7.egg/conveyor/address.py", line 102, in listen
    os.remove(self._path)
OSError: [Errno 2] No such file or directory: '/var/run/conveyor/conveyord.socket'
2016-10-20 18:19:21,803 | ERROR | MainThread:140102925866752 | main.py:87 | conveyor.server.__main__.ServerMain:main | conveyord terminating with exit code 1`

**Comment by sircambridge** [comment]
workaround - I have to 

sudo apt-get remove conveyor
sudo apt-get remove makerware

and reinstall each time i reboot

**Comment by dudecc** [comment]
You could probably fix this by adding a few lines to /etc/systemd/system/conveyor.service in the `[Service]` section:

```
PermissionsStartOnly=true
ExecStartPre=/bin/mkdir -p /var/run/conveyor
ExecStartPre=/bin/chown conveyor:conveyor /var/run/conveyor
ExecStartPre=/bin/chmod 775 /var/run/conveyor
```

(basically all of [this noise](https://github.com/makerbot/conveyor/blob/master/data/conveyor.conf#L18-L22) converted to systemd speak.)

**Comment by tomkcook** [comment]
This has also fixed a problem for me where conveyor just segfaults when started, except after reinstalling.

**Comment by Harakan** [comment]
@dudecc solution works in the ubuntu 16.04 ppa version as well with one caveat:

You still need to manually start the service after opening makerware.

**Comment by RetGal** [comment]
@dudecc your solution also works with Debian 8 (Jessie). 
Manual restart of the BackgroundService after opening MakerBot Desktop is required as well

**Comment by ganton516** [comment]
I was having a similar problem with 16.04.3.
I finally found that by changing the ownership of /var/run/conveyor fixed the start up problem:

sudo chown -R conveyor:conveyor /var/run/conveyor

Hope this helps
