### ISSUE TITLE
printtofile - unhandled exception

### ISSUE THREAD

**Issue by tbuser** [makerbot/conveyor#4]
With common settings:

{ "common":
    { "socket": "unix:conveyord.socket"
    , "slicer": "skeinforge"
    , "profile": "ReplicatorSingle"
    }

Running this to turn .gcode into .s3g:

cd /home/thingiv3rse/conveyor;/home/thingiv3rse/conveyor/conveyor -c /home/thingiv3rse/conveyor/conveyor-ReplicatorSingle-skeinforge.conf printtofile '/home/thingiv3rse/_zips/dev/ce1f8a5b2e1dd52bda2d9c916f8ac1d17d802dab/20mmbox.gcode' '/home/thingiv3rse/_zips/dev/ce1f8a5b2e1dd52bda2d9c916f8ac1d17d802dab/20mmbox.s3g' 2>&1

Results in:

2012-06-15 18:55:15,835 - INFO - slicing with Skeinforge
2012-06-15 18:55:43,727 - INFO - job 0 ended
2012-06-15 18:55:43,729 - INFO - slicing: /home/thingiv3rse/_zips/dev/ce1f8a5b2e1dd52bda2d9c916f8ac1d17d802dab/20mmbox -> /home/thingiv3rse/_zips/dev/ce1f8a5b2e1dd52bda2d9c916f8ac1d17d802dab/20mmbox.gcode (job 0)
2012-06-15 18:55:44,023 - INFO - printing to file: /home/thingiv3rse/_zips/dev/ce1f8a5b2e1dd52bda2d9c916f8ac1d17d802dab/20mmbox.gcode -> /home/thingiv3rse/_zips/dev/ce1f8a5b2e1dd52bda2d9c916f8ac1d17d802dab/20mmbox.s3g (job 1)
2012-06-15 18:55:44,026 - INFO - gcode: (***\* start.gcode for The Replicator, dual head ***_)
2012-06-15 18:55:44,026 - INFO - {u'totallines': 4891, u'currentbyte': 53, u'currentline': 0, u'totalbytes': 135351}
2012-06-15 18:55:44,026 - INFO - gcode: M73 P0 (enable build progress)
2012-06-15 18:55:44,027 - INFO - {u'totallines': 4891, u'currentbyte': 83, u'currentline': 1, u'totalbytes': 135351}
2012-06-15 18:55:44,027 - INFO - gcode: G21 (set units to mm)
2012-06-15 18:55:44,027 - INFO - {u'totallines': 4891, u'currentbyte': 104, u'currentline': 2, u'totalbytes': 135351}
2012-06-15 18:55:44,028 - INFO - gcode: G90 (set positioning to absolute)
2012-06-15 18:55:44,028 - INFO - {u'totallines': 4891, u'currentbyte': 137, u'currentline': 3, u'totalbytes': 135351}
2012-06-15 18:55:44,028 - INFO - gcode: G10 P1 X-16.5 Y0 Z0 (Designate T0 Offset)
2012-06-15 18:55:44,028 - INFO - {u'totallines': 4891, u'currentbyte': 178, u'currentline': 4, u'totalbytes': 135351}
2012-06-15 18:55:44,028 - INFO - gcode: G10 P2 X16.5 Y0 Z0 (Designate T1 Offset)
2012-06-15 18:55:44,029 - INFO - {u'totallines': 4891, u'currentbyte': 218, u'currentline': 5, u'totalbytes': 135351}
2012-06-15 18:55:44,029 - INFO - gcode: G54 (Recall offset cooridinate system)
2012-06-15 18:55:44,029 - INFO - {u'totallines': 4891, u'currentbyte': 256, u'currentline': 6, u'totalbytes': 135351}
2012-06-15 18:55:44,029 - INFO - gcode: (**_\* begin homing ***_)
2012-06-15 18:55:44,030 - INFO - {u'totallines': 4891, u'currentbyte': 280, u'currentline': 7, u'totalbytes': 135351}
2012-06-15 18:55:44,029 - INFO - gcode: G162 X Y D500(home XY axes maximum)
2012-06-15 18:55:44,030 - INFO - {u'totallines': 4891, u'currentbyte': 315, u'currentline': 8, u'totalbytes': 135351}
2012-06-15 18:55:44,030 - INFO - gcode: G161 Z D500(home Z axis minimum)
2012-06-15 18:55:44,031 - INFO - {u'totallines': 4891, u'currentbyte': 347, u'currentline': 9, u'totalbytes': 135351}
2012-06-15 18:55:44,031 - INFO - gcode: G92 X0 Y0 Z-5 A0 B0 (set Z to -5)
2012-06-15 18:55:44,031 - INFO - {u'totallines': 4891, u'currentbyte': 380, u'currentline': 10, u'totalbytes': 135351}
2012-06-15 18:55:44,031 - INFO - gcode: G1 Z0.0 F2500(move Z to '0')
2012-06-15 18:55:44,032 - INFO - {u'totallines': 4891, u'currentbyte': 408, u'currentline': 11, u'totalbytes': 135351}
2012-06-15 18:55:44,032 - INFO - gcode: G161 Z D1100(home Z axis minimum)
2012-06-15 18:55:44,032 - INFO - {u'totallines': 4891, u'currentbyte': 441, u'currentline': 12, u'totalbytes': 135351}
2012-06-15 18:55:44,032 - INFO - gcode: M132 X Y Z A B (Recall stored home offsets for XYZAB axis)
2012-06-15 18:55:44,033 - INFO - {u'totallines': 4891, u'currentbyte': 499, u'currentline': 13, u'totalbytes': 135351}
2012-06-15 18:55:44,033 - INFO - gcode: (**_\* end homing ***_)
2012-06-15 18:55:44,033 - INFO - {u'totallines': 4891, u'currentbyte': 521, u'currentline': 14, u'totalbytes': 135351}
2012-06-15 18:55:44,033 - INFO - gcode: G92 X112 Y73 Z0 A0 B0
2012-06-15 18:55:44,033 - INFO - {u'totallines': 4891, u'currentbyte': 542, u'currentline': 15, u'totalbytes': 135351}
2012-06-15 18:55:44,034 - INFO - gcode: G1 X-112 Y-73 Z150 F3300.0 (move to waiting position)
2012-06-15 18:55:44,034 - INFO - {u'totallines': 4891, u'currentbyte': 595, u'currentline': 16, u'totalbytes': 135351}
2012-06-15 18:55:44,034 - INFO - gcode: G130 X0 Y0 A0 B0 (Lower stepper Vrefs while heating)
2012-06-15 18:55:44,034 - INFO - {u'totallines': 4891, u'currentbyte': 647, u'currentline': 17, u'totalbytes': 135351}
2012-06-15 18:55:44,035 - INFO - gcode: M109 S100 T0 (set platform temperature)
2012-06-15 18:55:44,035 - INFO - {u'totallines': 4891, u'currentbyte': 686, u'currentline': 18, u'totalbytes': 135351}
2012-06-15 18:55:44,035 - INFO - gcode: M134 T0 (wait for platform to reach temperature)
2012-06-15 18:55:44,035 - INFO - {u'totallines': 4891, u'currentbyte': 734, u'currentline': 19, u'totalbytes': 135351}
2012-06-15 18:55:44,035 - INFO - gcode: M104 S220 T0 (set extruder 0 temperature)
2012-06-15 18:55:44,036 - INFO - {u'totallines': 4891, u'currentbyte': 775, u'currentline': 20, u'totalbytes': 135351}
2012-06-15 18:55:44,036 - INFO - gcode: M133 T0 (wait for extruder 0 to reach temperature)
2012-06-15 18:55:44,036 - INFO - {u'totallines': 4891, u'currentbyte': 825, u'currentline': 21, u'totalbytes': 135351}
2012-06-15 18:55:44,036 - INFO - gcode: G130 X127 Y127 A127 B127 (Set Stepper motor Vref to defaults)
2012-06-15 18:55:44,037 - INFO - {u'totallines': 4891, u'currentbyte': 886, u'currentline': 22, u'totalbytes': 135351}
2012-06-15 18:55:44,037 - INFO - gcode: M135 T0
2012-06-15 18:55:44,037 - INFO - {u'totallines': 4891, u'currentbyte': 893, u'currentline': 23, u'totalbytes': 135351}
2012-06-15 18:55:44,037 - INFO - gcode: G1 Z0.2      (Position Height)
2012-06-15 18:55:44,038 - INFO - {u'totallines': 4891, u'currentbyte': 923, u'currentline': 24, u'totalbytes': 135351}
2012-06-15 18:55:44,038 - INFO - gcode: G1 A2.0      (Create Anchor)
2012-06-15 18:55:44,038 - INFO - {u'totallines': 4891, u'currentbyte': 951, u'currentline': 25, u'totalbytes': 135351}
2012-06-15 18:55:44,038 - INFO - gcode: M101         (Start Extruder)
2012-06-15 18:55:44,038 - INFO - {u'totallines': 4891, u'currentbyte': 980, u'currentline': 26, u'totalbytes': 135351}
2012-06-15 18:55:44,039 - INFO - gcode: (**_\* end of start.gcode ***_)
2012-06-15 18:55:44,039 - INFO - {u'totallines': 4891, u'currentbyte': 1010, u'currentline': 27, u'totalbytes': 135351}
2012-06-15 18:55:44,039 - INFO - gcode: (**_\* start.gcode for The Replicator, single head ***_)
2012-06-15 18:55:44,039 - INFO - {u'totallines': 4891, u'currentbyte': 1066, u'currentline': 28, u'totalbytes': 135351}
2012-06-15 18:55:44,040 - INFO - gcode: M73 P0 (enable build progress)
2012-06-15 18:55:44,040 - INFO - {u'totallines': 4891, u'currentbyte': 1097, u'currentline': 29, u'totalbytes': 135351}
2012-06-15 18:55:44,040 - INFO - gcode: G21 (set units to mm)
2012-06-15 18:55:44,040 - INFO - {u'totallines': 4891, u'currentbyte': 1119, u'currentline': 30, u'totalbytes': 135351}
2012-06-15 18:55:44,040 - INFO - gcode: G90 (set positioning to absolute)
2012-06-15 18:55:44,041 - INFO - {u'totallines': 4891, u'currentbyte': 1153, u'currentline': 31, u'totalbytes': 135351}
2012-06-15 18:55:44,041 - INFO - gcode: M109 S110 T0 (set HBP temperature)
2012-06-15 18:55:44,101 - INFO - {u'totallines': 4891, u'currentbyte': 1188, u'currentline': 32, u'totalbytes': 135351}
2012-06-15 18:55:44,101 - INFO - gcode: M104 S220 T0 (set extruder temperature)
2012-06-15 18:55:44,102 - INFO - {u'totallines': 4891, u'currentbyte': 1228, u'currentline': 33, u'totalbytes': 135351}
2012-06-15 18:55:44,102 - INFO - gcode: (**_\* begin homing ****)
2012-06-15 18:55:44,102 - INFO - {u'totallines': 4891, u'currentbyte': 1253, u'currentline': 34, u'totalbytes': 135351}
2012-06-15 18:55:44,102 - INFO - gcode: G162 X Y F2500 (home XY axes maximum
2012-06-15 18:55:44,102 - ERROR - unhandled exception
Traceback (most recent call last):
  File "/home/thingiv3rse/conveyor/src/main/python/conveyor/printer/s3g.py", line 120, in runningcallback
    self._genericprint(task, writer, False, gcodepath)
  File "/home/thingiv3rse/conveyor/src/main/python/conveyor/printer/s3g.py", line 86, in _genericprint
    parser.ExecuteLine(data)
  File "/home/thingiv3rse/conveyor/submodule/s3g/s3g/Gcode/parser.py", line 113, in ExecuteLine
    raise gcode_error
InvalidCodeError: Command: G162 X Y F2500 (home XY axes maximum; InvalidCodes: F; LineNumber: 36
2012-06-15 18:55:44,103 - INFO - job 1 failed

**Comment by msamsonoff** [comment]
This is either an issue with the s3g driver or the s3g driver's start gcode. I'll talk with David and Matt Mets about this issue.

**Comment by msamsonoff** [comment]
Matt Mets and David Sayles have a fix for this. It's pending review and should be merged soon.

**Comment by tbuser** [comment]
Just tried latest pull from master and now I'm getting a new error:

2012-06-21 22:16:09,183 - ERROR - uncaught exception
Traceback (most recent call last):
  File "/home/thingiv3rse/conveyor/src/main/python/conveyor/jsonrpc.py", line 392, in _invokemethod
    result = func(_args, *_kwargs)
  File "/home/thingiv3rse/conveyor/src/main/python/conveyor/server/__init__.py", line 100, in _slice
    recipe = recipemanager.getrecipe(thing)
  File "/home/thingiv3rse/conveyor/src/main/python/conveyor/recipe.py", line 52, in getrecipe
    recipe = self._getrecipe_thing(path)
  File "/home/thingiv3rse/conveyor/src/main/python/conveyor/recipe.py", line 80, in _getrecipe_thing
    recipe = self._getrecipe_thing_dir(path)
  File "/home/thingiv3rse/conveyor/src/main/python/conveyor/recipe.py", line 98, in _getrecipe_thing_dir
    manifest = conveyor.path.Manifest.frompath(manifestpath)
AttributeError: 'module' object has no attribute 'path'

**Comment by tbuser** [comment]
I believe this has been fixed.
