### ISSUE TITLE
logging module dictConfig is not available on the Mac

### ISSUE THREAD

**Issue by msamsonoff** [makerbot/conveyor#6]
This is another Python 2.7 feature that isn't available on the Mac. We should be able to backport the method (if someone hasn't already done so).

**Comment by cera** [comment]
Example output

(virtualenv)[1347] [c@Chris-Ceras-MacBook-Air:~/makerbot/conveyor]
$ ./conveyor
Traceback (most recent call last):
  File "src/main/python/conveyor/client/**main**.py", line 168, in <module>
    sys.exit(_main(sys.argv))
  File "src/main/python/conveyor/client/__main__.py", line 162, in _main
    conveyor.log.earlylogging('conveyor')
  File "/Users/c/makerbot/conveyor/src/main/python/conveyor/log.py", line 78, in earlylogging
    logging.config.dictConfig(dct)
AttributeError: 'module' object has no attribute 'dictConfig'

**Comment by cera** [comment]
I closed this by accident previously.
